version: '2.3'
services:

  wasa-webdis:
    container_name: wasa-webdis
    image: nicolas/webdis
    ports:
      - "80:7379"

  wasa-webapp:
    container_name: wasa-webapp
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      WASA_API_HOSTNAME: wasa-api.ghs.bitknife.se
      WASA_API_PORT: 80
    depends_on:
      - wasa-webdis
