version: '2.3'
services:

  wasa-webdis:
    container_name: wasa-webdis
    image: nicolas/webdis
    ports:
      - "7379:80"

  wasa-webapp:
    container_name: wasa-webapp
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - wasa-webdis
